### Pandas Intro and Functions

In [ ]:
import pandas as pd

In [70]:
df=pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

df.head(10)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01
5,MSI Crosshair 17 C12VF-264XES Intel Core i7-12...,New,MSI,Crosshair,Intel Core i7,32,1000,SSD,RTX 4060,17.3,No,1699.00
6,Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8G...,New,Lenovo,ThinkPad,AMD Ryzen 5,8,256,SSD,NaN,14.0,No,909.00
7,ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-...,New,Asus,VivoBook,Intel Core i7,8,512,SSD,NaN,15.6,No,809.01
8,Medion Akoya E15415 Intel Core i5-10210U/8GB/2...,New,Medion,Akoya,Intel Core i5,8,256,SSD,NaN,15.6,No,519.00
9,HP Victus 16-d1038ns Intel Core i7-12700H/16GB...,New,HP,Victus,Intel Core i7,16,512,SSD,RTX 3050,16.1,No,1149.00

In [71]:
pd.__version__

'3.0.0'

In [72]:
#ROWS & COLUMNS
df.shape

(2160, 12)

In [73]:
##index

df.index

##accesing elements in df use loc funtion 
df.loc[[1,2,8]] ### loc is label based incase index has labels else it would work in our case we have numbers
df.loc[1:3]

df.iloc[1:2] ## iloc is used when we are accessing elements if index is integer

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0

#### string operations

In [74]:
df['Laptop'].str.lower()
df['Laptop'].str.upper()
df['Laptop'].str.capitalize()

0       Asus expertbook b1 b1502cba-ej0436x intel core...
1       Alurin go start intel celeron n4020/8gb/256gb ...
2       Asus expertbook b1 b1502cba-ej0424x intel core...
3       Msi katana gf66 12uc-082xes intel core i7-1270...
4       Hp 15s-fq5085ns intel core i5-1235u/16gb/512gb...
                              ...
2155    Razer blade 17 fhd 360hz intel core i7-11800h/...
2156    Razer blade 17 fhd 360hz intel core i7-11800h/...
2157    Razer blade 17 fhd 360hz intel core i7-11800h/...
2158    Razer book 13 intel evo core i7-1165g7/16gb/1t...
2159    Razer book fhd+ intel evo core i7-1165g7/16gb/...
Name: Laptop, Length: 2160, dtype: str

##### sumarizing operators

In [75]:
print(df['Final Price'].max())
print(df['Screen'].median())
print(round(df['Final Price'].sum(),2))

7150.47
15.6
2835299.18

In [76]:
df.describe().round(2)

           RAM  Storage   Screen  Final Price
count  2160.00  2160.00  2156.00      2160.00
mean     15.41   596.29    15.17      1312.64
std       9.87   361.22     1.20       911.48
min       4.00     0.00    10.10       201.05
25%       8.00   256.00    14.00       661.08
50%      16.00   512.00    15.60      1031.95
75%      16.00  1000.00    15.60      1708.97
max     128.00  4000.00    18.00      7150.47

In [77]:
## unique string values

df.Brand.nunique()

df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [78]:

## summarized form
print(df['Brand'].unique())

<StringArray>
[            'Asus',           'Alurin',              'MSI',
               'HP',           'Lenovo',           'Medion',
             'Acer',            'Apple',            'Razer',
         'Gigabyte',             'Dell',               'LG',
          'Samsung',            'PcCom',        'Microsoft',
           'Primux',          'Prixton', 'Dynabook Toshiba',
          'Thomson',           'Denver',      'Deep Gaming',
             'Vant',           'Innjoo',          'Jetwing',
        'Millenium',           'Realme',          'Toshiba']
Length: 27, dtype: str

#### Missing Values

In [79]:
## NULLS IF ANY
df.isna().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [80]:
df.isnull()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
2155,False,False,False,False,False,False,False,False,False,False,False,False
2156,False,False,False,False,False,False,False,False,False,False,False,False
2157,False,False,False,False,False,False,False,False,False,False,False,False
2158,False,False,False,False,False,False,False,False,True,False,False,False
2159,False,False,False,False,False,False,False,False,True,False,False,False

#### GROUPING

In [81]:
df.groupby('Brand').count()

,Laptop,Status,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
Brand,,,,,,,,,,,
Acer,137,137,137,137,137,137,137,51,136,137,137
Alurin,29,29,29,29,29,29,25,0,29,29,29
Apple,116,116,116,116,116,116,105,9,116,116,116
Asus,415,415,415,415,415,415,409,168,415,415,415
Deep Gaming,8,8,8,8,8,8,8,8,8,8,8
Dell,84,84,84,84,84,84,84,6,84,84,84
Denver,1,1,1,1,1,1,1,0,1,1,1
Dynabook Toshiba,19,19,19,19,19,19,19,0,19,19,19
Gigabyte,48,48,48,48,48,48,48,46,48,48,48
HP,368,368,368,368,368,368,361,87,367,368,368
Innjoo,6,6,6,6,6,6,6,0,6,6,6
Jetwing,1,1,1,1,1,1,1,0,1,1,1
LG,32,32,32,32,32,32,32,7,32,32,32
Lenovo,366,366,366,366,366,366,363,74,364,366,366
MSI,308,308,308,308,308,308,308,256,308,308,308
Medion,32,32,32,32,32,32,30,10,32,32,32
Microsoft,77,77,77,77,77,77,74,4,77,77,77
Millenium,2,2,2,2,2,2,2,2,2,2,2
PcCom,24,24,24,24,24,24,22,24,24,24,24
Primux,8,8,8,8,8,8,8,0,8,8,8
Prixton,3,3,3,3,3,3,1,0,3,3,3
Razer,37,37,37,37,37,37,37,35,37,37,37
Realme,1,1,1,1,1,1,1,0,1,1,1
Samsung,22,22,22,22,22,22,21,2,22,22,22
Thomson,4,4,4,4,4,4,3,0,4,4,4
Toshiba,1,1,1,1,1,1,1,0,1,1,1
Vant,11,11,11,11,11,11,11,0,11,11,11

In [82]:
df.groupby('Brand').Touch.count()

Brand
Acer                137
Alurin               29
Apple               116
Asus                415
Deep Gaming           8
Dell                 84
Denver                1
Dynabook Toshiba     19
Gigabyte             48
HP                  368
Innjoo                6
Jetwing               1
LG                   32
Lenovo              366
MSI                 308
Medion               32
Microsoft            77
Millenium             2
PcCom                24
Primux                8
Prixton               3
Razer                37
Realme                1
Samsung              22
Thomson               4
Toshiba               1
Vant                 11
Name: Touch, dtype: int64

In [83]:
df.groupby('Brand')['Final Price'].sum().round(0)

Brand
Acer                137176.0
Alurin               14056.0
Apple               183074.0
Asus                526793.0
Deep Gaming          12043.0
Dell                 96923.0
Denver                 330.0
Dynabook Toshiba     18985.0
Gigabyte             81527.0
HP                  350567.0
Innjoo                2087.0
Jetwing                469.0
LG                   55361.0
Lenovo              398107.0
MSI                 589343.0
Medion               28971.0
Microsoft           122857.0
Millenium             3954.0
PcCom                38562.0
Primux                2717.0
Prixton                877.0
Razer               120831.0
Realme                 999.0
Samsung              35101.0
Thomson               1267.0
Toshiba                799.0
Vant                 11522.0
Name: Final Price, dtype: float64